steps:
# Checkout your code
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ceebu/koelplayer.git'] 

# Setup Flutter environment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Or another suitable base image
  entrypoint: 'bash'
  args: 
    - '-c'
    - | curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.7.3-stable.tar.xz -o flutter.tar.xz && \  # Adjust Flutter version  
      tar xf flutter.tar.xz && \
      ./flutter/bin/flutter pub get && \ 
      ./flutter/bin/flutter build apk --release 

# Build the APK
- name: 'gcr.io/cloud-builders/dart'
  args: ['flutter', 'build', 'apk', '--release']
