steps:
# Checkout your code
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ceebu/koelplayer.git'] 

# Setup Flutter environment
- name: 'gcr.io/cloud-builders/dart'
  args: ['pub', 'get'] # Get Flutter dependencies

# Build the APK
- name: 'gcr.io/cloud-builders/dart'
  args: ['flutter', 'build', 'apk', '--release']
