steps:
- name: Checkout the code from Github
  uses: actions/checkout@v3
- name: Set up the Android environment
  uses: google/android-actions@v3
  with:
    sdk: google-services
- name: Build the Apk
  run: ./gradlew assembleRelease
